name: Build and test

on: [push]

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: build-and-test

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Configure nuget cache
      uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}
        restore-keys: |
          ${{ runner.os }}-nuget
        
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test UnitTests --no-restore
  
  release:
    if: ${{ github.ref == 'main' }}
    needs: build-and-test

    runs-on: ubuntu-latest
    name: release

    steps:
      - uses: actions/checkout@v2

      - name: Login to registry
        run: docker login rg.fr-par.scw.cloud/rocketshop -u nologin -p ${{ secrets.SCALEWAY_API_KEY }}

      - name: Build the Docker image
        run: docker build . -f API/Dockerfile --compress --tag rocketshop-api:$(date +%s) --label "created-by=github-actions" --label "project=API"

      - name: Tag image
        run: docker tag rocketshop-api:$(date +%s) rg.fr-par.scw.cloud/rocketshop/rocketshop-api:$(date +%s)

      - name: Push image to registry
        run: docker push rg.fr-par.scw.cloud/rocketshop/rocketshop-api:$(date +%s)
